sudo: required
language: python

python:
  - "3.6"

addons:
  postgresql: "9.6"
  apt:
    packages:
    - postgresql-9.6-postgis-2.4

services:
    - postgresql
    - docker
env:
    global:
        - SHA=$(git rev-parse HEAD)
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
    - pip install pipenv
    - pip install coveralls
    - pipenv install
    - sudo apt-get --quiet update
    - sudo apt-get install --yes libgdal-dev gdal-bin
before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://sdk.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project fluid-firefly-278811
    - gcloud config set compute/zone europe-west2-a
    - gcloud container clusters get-credentials commuters
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # - docker-compose build
    # - docker tag commuters-image $DOCKER_ID/commuters:1.1.3

    - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
    - psql -c "ALTER USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" -U $POSTGRES_USER
    - psql -c "create extension postgis" -U $POSTGRES_USER
    - psql -c "CREATE EXTENSION postgis_topology;" -U $POSTGRES_USER
    # - python manage.py migrate
script:
    - coverage run --source=app manage.py test
    - python -m coverage report -m

deploy:
    provider: script
    script: bash ./deploy.sh
    on:
        branch: develop