sudo: required
language: python
python:
- '3.6'
addons:
  postgresql: '9.6'
  apt:
    packages:
    - postgresql-9.6-postgis-2.4
services:
- postgresql
- docker
env:
  global:
  - SHA=$(git rev-parse HEAD)
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
install:
- pip install pipenv
- pip install coveralls
- pipenv install
# - pip install -r requirements.txt
- sudo apt-get --quiet update
- sudo apt-get install --yes libgdal-dev gdal-bin
before_install:
- openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
- curl https://sdk.cloud.google.com | bash > /dev/null;
- source $HOME/google-cloud-sdk/path.bash.inc
- gcloud components update kubectl
- gcloud auth activate-service-account --key-file service-account.json
- gcloud config set project commuters-278811
- gcloud config set compute/zone us-central1-a
- gcloud container clusters get-credentials commuters
# - gcloud container clusters get-credentials commuters --zone=us-central1-a
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
- psql -c 'create database test_commuters;' -U postgres
# - psql -c "create database $POSTGRES_DB;" -U $POSTGRES_USER
- psql -c "ALTER USER postgres WITH PASSWORD 'postgres';" -U postgres
- psql -c "create extension postgis" -U postgres
- psql -c "CREATE EXTENSION postgis_topology;" -U postgres
# script:

# - pipenv shell
# - pipenv run coverage run --source=app manage.py test --verbosity=2
# - python -m coverage report -m
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: ch-config-docker
