apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: postgres
    template:
        metadata:
            labels:
                component: postgres
        spec:
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                    claimName: database-pvc
            containers:
                - name: database
                  image: mdillon/postgis:10
                  ports:
                    - containerPort: 5432
                  volumeMounts:
                    - name: postgres-storage
                      mountPath: /var/lib/postgresql/data
                      subPath: postgres
                  env:
                    - name: POSTGRES_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: env-var
                            key: DB_PASSWORD
                    - name: POSTGRES_USER
                      value: postgres
                      # valueFrom:
                      #   secretKeyRef:
                      #       name: env-var
                      #       key: DB_USER
                    - name: POSTGRES_DB
                      valueFrom:
                        secretKeyRef:
                            name: env-var
                            key: DB_NAME
