# Generated by Django 2.2.9 on 2020-01-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fare',
            field=models.FloatField(blank=True, db_index=True, default=None, max_length=15, null=True),
        ),
    ]
