# Generated by Django 2.2.9 on 2020-01-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_vehicle_fare'),
        ('route', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='vehicle.Vehicle'),
        ),
    ]
