name: Deploy Finance web api

on:
  push:
    branches: [ deploy-eks ]
env:
  AWS_REGION: us-east-1                  
  ECR_REPOSITORY: commuters         

jobs:
  dev_build_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build --file docker/Dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:dev-$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:dev-$IMAGE_TAG
    - name: deploy to cluster
      uses: kodermax/kubectl-aws-eks@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.DEV_EKS_KUBECONFIG }}
        # KUBECTL_VERSION: ${{ secrets.KUBECTL_VERSION }}
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: $ECR_REPOSITORY
        IMAGE_TAG: ${{ github.sha }}
      with:
        args: set image deployment/server-deployment server-deployment=$ECR_REGISTRY/commuters:dev-$IMAGE_TAG